### ISSUE TITLE
Ajouter une page 404

### ISSUE THREAD

**Issue by Bigaston** [Bigaston/youpod#103]

**Comment by PhilGoud** [comment]
tu veux quoi dans ta page 404 ?

**Comment by Bigaston** [comment]
Ouaip carrément!

**Comment by PhilGoud** [comment]
J'ai réutilisé l'élément "success"
je vais peut-être le changer de nom alors

**Comment by PhilGoud** [comment]
l'élément "success" est devenu "message" dans la dernière version
