### ISSUE TITLE
Retours beta

### ISSUE THREAD

**Issue by PhilGoud** [Bigaston/youpod#110]
- appliquer la class logo sur l'image du logo (80% de la largeur)
- un peu de margin sous le logo
- ne pas ajouter d'ombre au hover sur l'étape actuelle
- bouton "Analyser" en class  bigbutton (comme convertir mais avec le analyze.svg)
- Mettre un loader le temps de l'analyse du flux (utiliser https://loading.io/ au besoin)
- ne pas mettre les boutons suivants et retours tant que le flux n'est pas analysé
- mettre type="url" dans l'input du RSS
- mettre une erreur si l'adresse n'est pas un flux RSS
- stp : peu ou pas d'animation au changement de page (fait du caca actuellement et rend l'expérience moins snappy)

**Comment by PhilGoud** [comment]
mettre un message indiquant la limite de 119s dans le champs de durée de l'extrait

**Comment by Bigaston** [comment]
- Supprimer les transitions et animations
- Cacher le 1-2-3 quand on est sur la page de conclusion
- Changer le CSS du login pour mettre en place le nouveau CSS

**Comment by PhilGoud** [comment]
logo non cliquable pour retour à la homepage

**Comment by Bigaston** [comment]
Juste histoire d'avoir des checkbox xD

- [ ] appliquer la class logo sur l'image du logo (80% de la largeur)
- [ ] un peu de margin sous le logo
- [ ] ne pas ajouter d'ombre au hover sur l'étape actuelle
- [ ] bouton "Analyser" en class bigbutton (comme convertir mais avec le analyze.svg)
- [ ] Mettre un loader le temps de l'analyse du flux (utiliser https://loading.io/ au besoin)
- [ ] ne pas mettre les boutons suivants et retours tant que le flux n'est pas analysé
- [ ] mettre type="url" dans l'input du RSS
- [ ] mettre une erreur si l'adresse n'est pas un flux RSS
- [ ] mettre un message indiquant la limite de 119s dans le champs de durée de l'extrait
- [ ] Supprimer les transitions et animations
- [ ] Cacher le 1-2-3 quand on est sur la page de conclusion
- [ ] Changer le CSS du login pour mettre en place le nouveau CSS
- [ ] logo non cliquable pour retour à la homepage
