### ISSUE TITLE
Permlettre URL localhost

### ISSUE THREAD

**Issue by cestoliv** [Bigaston/youpod#112]
Bonjour !
J'ai installé YouPod chez moi et en voulant envoyer une vidéo de mon PC, j'ai rentré les URL suivantes :
`http://localhost:8000/cover.png`
`http://localhost:8000/EMPTY.png`
et j'obtiens ainsi l'erreur : 

`Unhandled rejection SequelizeValidationError: Validation error: Validation isUrl on imgLink failed,
Validation error: Validation isUrl on audioLink failed
`
 ##
J'ai pu parvenir à mes fins en commentant la ligne 74 du fichier suivant : `youpod/node_modules/sequelize/libinstance-validator.js` mais je ne pense pas que ce soit une solution viable...

Merci encore pour ce super outil !

**Comment by Bigaston** [comment]
Salut!
J'aurais quelques petites questions. Comment tu as fais pour avoir tes fichiers avec une adresse sur le port 8000 comme ça? Avec un serveur local?

Et, tu as essayé de faire la même chose mais avec une adresse avec file:// ?

Sinon, je vais essayer de voir pour régler ce problème, en différenciant une instance locale d'une instance distante.

**Comment by cestoliv** [comment]
Hello !
Ouais un petit serveur local en python, en fait je voulais le faire pour un sons qui n'était pas encore en ligne. J'ai d'abord essayé avec le file:// mais ça ne fonctionnait pas (je ne me rappel plus de l'erreur).
Merci en touts cas de t'en soucier, mais peut être que sans forcément savoir si c'est une instance local, autoriser le format d'URL sans nom de domaine suffirait (IP:port) ?

**Comment by Bigaston** [comment]
En fait le problème que j'aurais à autoriser le localhost, c'est que sur l'instance en ligne ça serait une bonne faille de sécu, et surtout ça risque de causer encore plus de soucis (j'ai pas encore tout super bien sécurisé).
Mais du coup je vais essayer de mettre en place une solution temporaire sur la 2.0 (qui sortira pas de suite mais c'est le plus tôt que je puisse faire ^^'), qui serait une option pour dire si on autorise les origines Localhost ou pas. Et ensuite ce soucis sera totalement réglé quand on passera sur un "simple" file picker pour les fichiers et les images (pas de suites, mais c'est prévu)

**Comment by cestoliv** [comment]
Oui effectivement, je n'avais pas pensé à ce problème... En tout cas merci beaucoup pour tout le travail effectué, hâte de voir un file picker !

**Comment by Bigaston** [comment]
Merci d'utiliser ce qu'on fait!

Le filepicker n'arrivera pas tout de suite, je préfère me concentrer pour sortir la 2.0 même en beta, proprement, mais après je m'en chargerais ^^

**Comment by Bigaston** [comment]
Au final, j’implémenterais pas d'option pour le moment ^^' Mais je tafferais sur le file picker dés la prochaine version
