### ISSUE TITLE
Emojis 

### ISSUE THREAD

**Issue by PhilGoud** [Bigaston/youpod#121]
en gros : ça chie dans les générations alors que le reste marche, du coup on le voit pas venir que ça va faire de la merde

![image](https://user-images.githubusercontent.com/17003249/75435334-2cfa9a00-5953-11ea-801c-78724a1f977e.png)

là ça chie pas par contre : 
![image](https://user-images.githubusercontent.com/17003249/75435370-35eb6b80-5953-11ea-9da1-6f283a08758a.png)
![image](https://user-images.githubusercontent.com/17003249/75435452-54516700-5953-11ea-80ab-4045940e6f03.png)

**Comment by PhilGoud** [comment]
flux pour tester : https://lacheyvocomz.lepodcast.fr/rss
Episode 12

**Comment by Bigaston** [comment]
Je vais utiliser ce que Pof avait proposé, Tweetmoji ^^
