### ISSUE TITLE
Sécurité anti spam

### ISSUE THREAD

**Issue by Bigaston** [Bigaston/youpod#15]
CSRF? Pas deux fois la même vidéo?

**Comment by Bigaston** [comment]
CSRF Ok

**Comment by PofMagicfingers** [comment]
Je pense qu'il faut vérifier qu'on puisse pas faire la même demande (url audio et image etc) 2x de suite en moins de 1h. Et mettre un message d'erreur genre "Cette vidéo à déjà été générée voici le lien" ou "Cette vidéo est en cours de génération"

Et avoir ce retour aussi dans l'api. Quand tu demandes une génération ça te renvoie l'id et le status, bah là si c'est déjà généré ça t'envoie direct le statut deja fait avec le lien.

**Comment by Bigaston** [comment]
Je pense que ouaip c'est le plus simple à faire, je pensais faire quelque chose dans le genre, mais de toute façon l'API doit être améliorée
