### ISSUE TITLE
Choix de police dynamique

### ISSUE THREAD

**Issue by PhilGoud** [Bigaston/youpod#17]
(Si possible)
Permettre un choix dans la google font
https://github.com/samuelmeuli/font-picker
sinon
https://www.jqueryscript.net/text/Easy-Google-Web-Font-Selector-With-jQuery-Fontselect.html

**Comment by Bigaston** [comment]
Ca devrait être possible à faire, mais il faudrait que je regarde comment l'intégrer dans le template...

**Comment by PhilGoud** [comment]
ALORS, c'est pas hyper compliqué, tu "moustaches" la font dans <style>

**Comment by PhilGoud** [comment]
body{
                margin: 0px;
                height: 100%;
                width: 100%;
               font-family: {{{ Gfont }}};
            }

**Comment by PhilGoud** [comment]
par contre il faudra une police par défaut^^
à faire après le preview je pense, de toute façon
