### ISSUE TITLE
Refonte UX pour permettre les RS

### ISSUE THREAD

**Issue by PhilGoud** [Bigaston/youpod#29]

**Comment by Bigaston** [comment]
On va peut être pas mettre directement Youtube en gros, mais plutôt remplacer par Video?

**Comment by PhilGoud** [comment]
![Maquette v1 2 (2)](https://user-images.githubusercontent.com/17003249/71823289-2d835c80-3097-11ea-9a8c-2c30440b4013.jpg)

**Comment by PhilGoud** [comment]
https://stackoverflow.com/questions/14961246/how-to-get-current-users-profile-information-in-youtube-data-api-v3
