### ISSUE TITLE
[admin] Mettre le titre dans le titre

### ISSUE THREAD

**Issue by PhilGoud** [Bigaston/youpod#50]
![unknown](https://user-images.githubusercontent.com/17003249/71361871-98f80500-2594-11ea-8f61-81fe8127d94a.png)
à l'heure actuelle le titre est l'adresse du flux.

Mettre le titre de l'épisode et/ou le titre du podcast (avec une limite de nombre de caractères)

ex ici il faudrait écrire : 

> [ASpaceMR] Premières obser...

**Comment by PhilGoud** [comment]
alternative : seul le titre du podcast est présent (dans ce cas changer le nom de la colonne) et l'épisode peut être lu en passant la souris sur la ligne concernée

**Comment by Bigaston** [comment]
Alors en fait dans mon ébauche j'avais Titre/RSS parce que à cet endroit là j'avais le RSS pour la génération avec RSS et le titre dans custom, comme ça pas de requete sur le flux de manière inutile
