### ISSUE TITLE
Ajouter la clef API YouTube à l'admin

### ISSUE THREAD

**Issue by PhilGoud** [Bigaston/youpod#64]

**Comment by Bigaston** [comment]
En fait je me dis que quelque chose d'aussi sensible que ça doit pouvoir s'ajouter seulement dans le .env

**Comment by PhilGoud** [comment]
c'est pas plus ou moins sensible que la clef api des fonts
et puis c'est une clef api justement, pas un mdp

**Comment by Bigaston** [comment]
C'est pas faux
