### ISSUE TITLE
Balise meta data (OpenGraph)

### ISSUE THREAD

**Issue by Bigaston** [Bigaston/youpod#68]
OpenGraph

**Comment by PhilGoud** [comment]
https://webcode.tools/open-graph-generator

**Comment by PhilGoud** [comment]
`<meta property="og:title" content="YouPod">
<meta property="og:site_name" content="YouPod">
<meta property="og:url" content="https://youpod.io">
<meta property="og:description" content="Partagez gratuitement votre podcast audio en vidéo Publiez vos créations audio sur YouTube et les réseaux sociaux, une émission complète ou un extrait. C’est gratuit, rapide et sans inscription !">
<meta property="og:type" content="website">
<meta property="og:image" content="https://beta.youpod.io/static/icon.png">`
