### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by PhilGoud** [Bigaston/youpod#75]
![image](https://user-images.githubusercontent.com/17003249/72078148-df6d9380-32f8-11ea-8c03-31ed053ba749.png)
Revoir la page d'accueil pour améliorer ce SEO catastrophique^^

**Comment by Bigaston** [comment]
On peut pas mettre la description via les OpenGraph?

**Comment by Bigaston** [comment]
Si on peut améliorer le SEO avant le lancement de la V2, c'est cool

Aussi penser à remettre les favicons
