### ISSUE TITLE
Alléger l'interface des trucs inutiles au début

### ISSUE THREAD

**Issue by PhilGoud** [Bigaston/youpod#86]
Lorsque les champs ne sont pas pertinents maintenant, autant ne pas les mettre^^

Exemple sur /index
Ne mettre que : 
- bouton connexion YT
- Champs d'URL flux

Tant que le flux n'est pas parsé : 
- pas besoin du select d'épisode
- pas besoin du mail
- pas besoin du mode avancé
- pas besoin du bouton conversion

![image](https://user-images.githubusercontent.com/17003249/72663964-9e603800-39f8-11ea-87ce-24dffa2b7edc.png)

Exemple sur /socials
Tant que le flux n'est pas parsé : 
- pas besoin du select d'épisode
- pas besoin du mail

![image](https://user-images.githubusercontent.com/17003249/72663967-afa94480-39f8-11ea-9cee-3b58306b6e50.png)

**Comment by PofMagicfingers** [comment]
Mon avis : 
c'est pas clair les deux boutons en haut, on a l'impression qu'on peu switch de l'un a l'autre sans recharger la page, je le mettrais plutot sur une page d’accueil a part vite fait, et je ferais un bouton retour sur chaque template extrait et full pour retourner sur cet accueil.

Et encore une fois : aperçu ou preview c'est pas clair, j'ai l'impression que ça permet de générer un "aperçu" de ce que je vais générer dans "Générer une vidéo". En vrai on génère de vidéos partout, donc ça serait plutôt : 

Générer une video :
[Episode complet] [Extrait]


Voilà !
