### ISSUE TITLE
Permettre l'upload du MP3 et de l'image lors du mode /custom

### ISSUE THREAD

**Issue by PhilGoud** [Bigaston/youpod#92]
Les supprimer à la fin du traitement (lors de l'envoi du mail ?)
Prévoir un nettoyage du dossier uploads qui supprime les fichiers plus vieux que 24h

**Comment by PhilGoud** [comment]
https://github.com/pqina/filepond

**Comment by Bigaston** [comment]
- Le client upload le fichier sur le serveur. Le serveur stock dans une table le nom du fichier, sa date d'upload, son type, mais laisse vide dans le champ qui dit avec quelle vidéo il est associé.
- Le serveur renvoit au client le nom du fichier (le timestamp ptet? Ou juste la clé primaire de la table?), qui l'ajoute dans mon objet qui représente toutes les infos.
- Au moment de l'ajout de la vidéo sur le serveur, il prend le nom, passé en paramètre, et va faire le lien entre le fichier et la vidéo
- A la fin du traitement, il supprime les lignes associés et le fichier en question

Et toutes les 5 minutes, il prend tous les fichiers, check si ça fait plus de 30 minutes qu'ils sont là sans être associé à une vidéo, et si c'est le cas ça les supprime
